In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
def read_pet(file):
    return(
    pd.read_csv(file,
               names=['cat_name', 'num_images', 'num_videos', 'age', 'breed',
                      'color', 'size', 'sex', 'characteristics', 'blank_coat_length',
                      'house_trained', 'health', 'good_in_a_home_with', 'adoption_fee',
                      'prefers_a_home_without', 'coat_length', 'pet_story_num_words',
                      'rescue_group', 'days_on_petfinder', 'special_needs']
               ))

In [23]:
def get_data(file,info):
    dsn = read_pet(file)
    dsn['data_set'] = info
    
    mask=dsn['special_needs'].isnull()
    
    dsn.loc[mask,'special_needs'] = dsn.loc[mask,'days_on_petfinder'] 
    dsn.loc[mask,'days_on_petfinder'] = dsn.loc[mask,'rescue_group'] 
    dsn.loc[mask,'rescue_group'] = dsn.loc[mask,'pet_story_num_words'] 
    dsn.loc[mask,'pet_story_num_words'] = dsn.loc[mask,'coat_length']  
    dsn.loc[mask,'coat_length'] = np.nan
    
    dsn['pet_story_num_words'] = pd.to_numeric(dsn['pet_story_num_words'],errors = 'coerce')
    return(dsn)

In [32]:
one_day = get_data('one_day.csv','one_day')
one_day.head()

,cat_name,num_images,num_videos,age,breed,color,size,sex,characteristics,blank_coat_length,...,health,good_in_a_home_with,adoption_fee,prefers_a_home_without,coat_length,pet_story_num_words,rescue_group,days_on_petfinder,special_needs,data_set
0,Ashe and Billie,6,0,Adult,Domestic Short Hair,NaN,Medium,Female,NaN,NaN,...,"Vaccinations up to date, spayed / neutered.",NaN,NaN,NaN,NaN,89.0,KittyKind,1,No,one_day
1,Billie and Ashe,6,0,Adult,Domestic Short Hair,NaN,Medium,Female,NaN,NaN,...,"Vaccinations up to date, spayed / neutered.",NaN,NaN,NaN,NaN,89.0,KittyKind,1,No,one_day
2,Holiday Hibiscus,2,0,Kitten,Domestic Short Hair,Gray / Blue / Silver,Medium,Male,NaN,NaN,...,Vaccinations up to date.,"Other cats, children.",NaN,NaN,Short,126.0,Liberty Humane Society,1,No,one_day
3,"Favorite Babies-Wonton, Lichee, Sprout & Dumpling",3,0,Kitten,Domestic Short Hair,White,Small,Male,NaN,NaN,...,NaN,Other cats.,NaN,NaN,NaN,313.0,Brooklyn Animal Action,1,No,one_day
4,Romeo and Guero,4,0,Young,Domestic Short Hair,NaN,Medium,Male,"Friendly, Affectionate, Gentle, Playful",NaN,...,"Vaccinations up to date, spayed / neutered.",NaN,NaN,NaN,Medium,149.0,The Lucky Cat Rescue,1,No,one_day

In [33]:
fourteen_day= get_data('fourteen_days.csv','fourteen_days')
fourteen_day.head()

,cat_name,num_images,num_videos,age,breed,color,size,sex,characteristics,blank_coat_length,...,health,good_in_a_home_with,adoption_fee,prefers_a_home_without,coat_length,pet_story_num_words,rescue_group,days_on_petfinder,special_needs,data_set
0,Sylvie,4,0,Adult,Domestic Short Hair,Tabby (Brown / Chocolate),Medium,Female,NaN,NaN,...,"Vaccinations up to date, spayed / neutered.",NaN,NaN,Children.,Short,263.0,City Critters Inc.,14,No,fourteen_days
1,Carrot,6,0,Kitten,Domestic Short Hair,Orange / Red,Small,Male,NaN,NaN,...,"Vaccinations up to date, spayed / neutered.","Other cats, children.",NaN,NaN,Short,109.0,City Critters Inc.,14,No,fourteen_days
2,Belle/Ollie,5,1,Kitten,Domestic Short Hair,Gray & White,Small,Female,NaN,NaN,...,"Vaccinations up to date, spayed / neutered.",NaN,NaN,NaN,Short,62.0,City Critters Inc.,14,No,fourteen_days
3,Mickey,4,0,Adult,Bombay & Domestic Short Hair Mix,Black,Medium,Male,"Friendly, Affectionate, Gentle, Playful, Curio...",NaN,...,Spayed / neutered.,"Other cats, dogs, children.",NaN,NaN,Short,126.0,Ready For Rescue,14,No,fourteen_days
4,Lah Lah,5,1,Senior,Domestic Short Hair,Black,Medium,Male,"Friendly, Playful, Curious, Brave, Smart, Funn...",NaN,...,"Vaccinations up to date, spayed / neutered.",Other cats.,NaN,NaN,Short,171.0,Ready For Rescue,14,No,fourteen_days

In [34]:
seven_days = get_data('seven_days.csv','seven_days')
seven_days.head()

,cat_name,num_images,num_videos,age,breed,color,size,sex,characteristics,blank_coat_length,...,health,good_in_a_home_with,adoption_fee,prefers_a_home_without,coat_length,pet_story_num_words,rescue_group,days_on_petfinder,special_needs,data_set
0,Sylvie,4,0,Adult,Domestic Short Hair,Tabby (Brown / Chocolate),Medium,Female,NaN,NaN,...,"Vaccinations up to date, spayed / neutered.",NaN,NaN,Children.,Short,263.0,City Critters Inc.,1,No,seven_days
1,Carrot,6,0,Kitten,Domestic Short Hair,Orange / Red,Small,Male,NaN,NaN,...,"Vaccinations up to date, spayed / neutered.","Other cats, children.",NaN,NaN,Short,109.0,City Critters Inc.,1,No,seven_days
2,Mickey,4,0,Adult,Bombay & Domestic Short Hair Mix,Black,Medium,Male,"Friendly, Affectionate, Gentle, Playful, Curio...",NaN,...,Spayed / neutered.,"Other cats, dogs, children.",NaN,NaN,Short,126.0,Ready For Rescue,1,No,seven_days
3,Lah Lah,5,1,Senior,Domestic Short Hair,Black,Medium,Male,"Friendly, Playful, Curious, Brave, Smart, Funn...",NaN,...,"Vaccinations up to date, spayed / neutered.",Other cats.,NaN,NaN,Short,171.0,Ready For Rescue,1,No,seven_days
4,Jackie,6,0,Young,Domestic Short Hair,NaN,Medium,Female,"Affectionate, Friendly, Gentle, Smart, Playful...",NaN,...,"Vaccinations up to date, spayed / neutered.","Other cats, dogs, children.",$300.00,NaN,Medium,165.0,"Good World Animal Rescue and Protection,â€¦",1,No,seven_days

In [35]:
spec_needs_all = get_data('spec_needs_all.csv','spec_needs_all')
spec_needs_all.head()

,cat_name,num_images,num_videos,age,breed,color,size,sex,characteristics,blank_coat_length,...,health,good_in_a_home_with,adoption_fee,prefers_a_home_without,coat_length,pet_story_num_words,rescue_group,days_on_petfinder,special_needs,data_set
0,Dougie,5,1,Senior,Domestic Short Hair,NaN,Medium,Female,NaN,NaN,...,"Spayed / neutered, special needs.",NaN,NaN,NaN,NaN,362.0,City Critters Inc.,special_needs_all,All,spec_needs_all
1,Elias,6,1,Adult,Domestic Short Hair,NaN,Medium,Male,NaN,NaN,...,"Spayed / neutered, special needs.",NaN,NaN,NaN,NaN,168.0,City Critters Inc.,special_needs_all,All,spec_needs_all
2,Beanie,5,0,Senior,Domestic Short Hair,Gray / Blue / Silver,Medium,Male,NaN,NaN,...,"Vaccinations up to date, spayed / neutered, sp...",NaN,NaN,Other cats.,Short,141.0,City Critters Inc.,special_needs_all,All,spec_needs_all
3,Jalapeno - NYC,6,0,Young,Domestic Short Hair,Black,Medium,Female,FIV positive,NaN,...,"Vaccinations up to date, spayed / neutered, sp...",NaN,NaN,NaN,NaN,285.0,Best Friends Animal Society - East Coast Lifeâ€¦,special_needs_all,All,spec_needs_all
4,Bambi - NYC,6,0,Adult,Domestic Short Hair,Black,Medium,Female,FIV positive,NaN,...,"Vaccinations up to date, spayed / neutered, sp...",NaN,NaN,NaN,NaN,180.0,Best Friends Animal Society - East Coast Lifeâ€¦,special_needs_all,All,spec_needs_all

In [30]:
thirty_day_spec_needs = get_data('thirty_day_spec_needs.csv','thirty_day_spec_needs')
thirty_day_spec_needs.head()

,cat_name,num_images,num_videos,age,breed,color,size,sex,characteristics,blank_coat_length,...,health,good_in_a_home_with,adoption_fee,prefers_a_home_without,coat_length,pet_story_num_words,rescue_group,days_on_petfinder,special_needs,data_set
0,Dougie,5,1,Senior,Domestic Short Hair,NaN,Medium,Female,NaN,NaN,...,"Spayed / neutered, special needs.",NaN,NaN,NaN,NaN,362.0,City Critters Inc.,30+,Special Needs 30+,thirty_day_spec_needs
1,Elias,6,1,Adult,Domestic Short Hair,NaN,Medium,Male,NaN,NaN,...,"Spayed / neutered, special needs.",NaN,NaN,NaN,NaN,168.0,City Critters Inc.,30+,Special Needs 30+,thirty_day_spec_needs
2,Beanie,5,0,Senior,Domestic Short Hair,Gray / Blue / Silver,Medium,Male,NaN,NaN,...,"Vaccinations up to date, spayed / neutered, sp...",NaN,NaN,Other cats.,Short,141.0,City Critters Inc.,30+,Special Needs 30+,thirty_day_spec_needs
3,Jalapeno - NYC,6,0,Young,Domestic Short Hair,Black,Medium,Female,FIV positive,NaN,...,"Vaccinations up to date, spayed / neutered, sp...",NaN,NaN,NaN,NaN,285.0,Best Friends Animal Society - East Coast Lifeâ€¦,30+,Special Needs 30+,thirty_day_spec_needs
4,Bambi - NYC,6,0,Adult,Domestic Short Hair,Black,Medium,Female,FIV positive,NaN,...,"Vaccinations up to date, spayed / neutered, sp...",NaN,NaN,NaN,NaN,180.0,Best Friends Animal Society - East Coast Lifeâ€¦,30+,Special Needs 30+,thirty_day_spec_needs

In [31]:
thirty_days = get_data('thirty_days.csv','thirty_days')
thirty_days.head()

,cat_name,num_images,num_videos,age,breed,color,size,sex,characteristics,blank_coat_length,...,health,good_in_a_home_with,adoption_fee,prefers_a_home_without,coat_length,pet_story_num_words,rescue_group,days_on_petfinder,special_needs,data_set
0,Pink,4,0,Adult,Domestic Short Hair,Gray / Blue / Silver,Medium,Female,Loving Playful Curious,NaN,...,"Vaccinations up to date, spayed / neutered.","Other cats, children.",NaN,NaN,Short,270.0,Big Hands Little Paws,30+,No,thirty_days
1,Panther,5,0,Kitten,Domestic Short Hair,Black,Small,Female,Loving Playful Curious Bonded,NaN,...,"Vaccinations up to date, spayed / neutered.","Other cats, children.",NaN,NaN,Short,287.0,Big Hands Little Paws,30+,No,thirty_days
2,Moo,4,0,Adult,Domestic Short Hair,Black & White / Tuxedo,Medium,Male,Loving Playful Curious Chill,NaN,...,"Vaccinations up to date, spayed / neutered.",NaN,NaN,NaN,NaN,239.0,Big Hands Little Paws,30+,No,thirty_days
3,Bread,6,0,Young,Domestic Short Hair,Calico,Medium,Female,"Loving, Playful, Curious, Bonded",NaN,...,"Vaccinations up to date, spayed / neutered.","Other cats, dogs, children.",NaN,NaN,Short,229.0,Big Hands Little Paws,30+,No,thirty_days
4,Ginger,6,0,Young,Domestic Short Hair,Orange & White,Medium,Female,"Loving, Playful, Curious, Bonded",NaN,...,"Vaccinations up to date, spayed / neutered.","Other cats, dogs, children.",NaN,NaN,Short,227.0,Big Hands Little Paws,30+,No,thirty_days

In [39]:


duplicate = combined_ex30[combined_ex30.duplicated(['cat_name', 'num_images', 'num_videos', 'age', 'breed', 'color', 'size', 'sex', 'characteristics', 'blank_coat_length', 'house_trained', 'health', 'good_in_a_home_with', 'adoption_fee', 'prefers_a_home_without', 'coat_length', 'pet_story_num_words', 'rescue_group'])]
#duplicate

In [63]:
combined_all = pd.concat([one_day, seven_days, fourteen_day, thirty_days ], axis = 0, sort=False)

#delete redundant columns
del combined_all['days_on_petfinder']
del combined_all['special_needs']
del combined_all['blank_coat_length']

#add for counting later
combined_all['num_cats'] = 1

#Export to csv
combined_all.to_csv('out_days_petfinder_combined.csv')
combined_all.head()

,cat_name,num_images,num_videos,age,breed,color,size,sex,characteristics,house_trained,health,good_in_a_home_with,adoption_fee,prefers_a_home_without,coat_length,pet_story_num_words,rescue_group,data_set,num_cats
0,Ashe and Billie,6,0,Adult,Domestic Short Hair,NaN,Medium,Female,NaN,Yes,"Vaccinations up to date, spayed / neutered.",NaN,NaN,NaN,NaN,89.0,KittyKind,one_day,1
1,Billie and Ashe,6,0,Adult,Domestic Short Hair,NaN,Medium,Female,NaN,Yes,"Vaccinations up to date, spayed / neutered.",NaN,NaN,NaN,NaN,89.0,KittyKind,one_day,1
2,Holiday Hibiscus,2,0,Kitten,Domestic Short Hair,Gray / Blue / Silver,Medium,Male,NaN,Yes,Vaccinations up to date.,"Other cats, children.",NaN,NaN,Short,126.0,Liberty Humane Society,one_day,1
3,"Favorite Babies-Wonton, Lichee, Sprout & Dumpling",3,0,Kitten,Domestic Short Hair,White,Small,Male,NaN,Yes,NaN,Other cats.,NaN,NaN,NaN,313.0,Brooklyn Animal Action,one_day,1
4,Romeo and Guero,4,0,Young,Domestic Short Hair,NaN,Medium,Male,"Friendly, Affectionate, Gentle, Playful",Yes,"Vaccinations up to date, spayed / neutered.",NaN,NaN,NaN,Medium,149.0,The Lucky Cat Rescue,one_day,1

In [64]:
spec_needs_combined = spec_needs_all.merge(thirty_day_spec_needs[['cat_name','rescue_group','data_set']],how='left',
                     on =['rescue_group','cat_name'])
mask=spec_needs_combined['data_set_y'].isnull()

spec_needs_combined.loc[mask,'data_set_y'] = 'spec_needs_other'
spec_needs_combined.columns = spec_needs_combined.columns.str.replace('data_set_y','data_set')

#delete redundant columns
del spec_needs_combined['days_on_petfinder']
del spec_needs_combined['special_needs']
del spec_needs_combined['data_set_x']
del spec_needs_combined['blank_coat_length']

#add for counting later
spec_needs_combined['num_cats'] = 1

#Export to csv
spec_needs_combined.to_csv('out_spec_needs_combined.csv')

spec_needs_combined.head()

,cat_name,num_images,num_videos,age,breed,color,size,sex,characteristics,house_trained,health,good_in_a_home_with,adoption_fee,prefers_a_home_without,coat_length,pet_story_num_words,rescue_group,data_set,num_cats
0,Dougie,5,1,Senior,Domestic Short Hair,NaN,Medium,Female,NaN,NaN,"Spayed / neutered, special needs.",NaN,NaN,NaN,NaN,362.0,City Critters Inc.,thirty_day_spec_needs,1
1,Elias,6,1,Adult,Domestic Short Hair,NaN,Medium,Male,NaN,NaN,"Spayed / neutered, special needs.",NaN,NaN,NaN,NaN,168.0,City Critters Inc.,thirty_day_spec_needs,1
2,Beanie,5,0,Senior,Domestic Short Hair,Gray / Blue / Silver,Medium,Male,NaN,Yes,"Vaccinations up to date, spayed / neutered, sp...",NaN,NaN,Other cats.,Short,141.0,City Critters Inc.,thirty_day_spec_needs,1
3,Jalapeno - NYC,6,0,Young,Domestic Short Hair,Black,Medium,Female,FIV positive,NaN,"Vaccinations up to date, spayed / neutered, sp...",NaN,NaN,NaN,NaN,285.0,Best Friends Animal Society - East Coast Lifeâ€¦,thirty_day_spec_needs,1
4,Bambi - NYC,6,0,Adult,Domestic Short Hair,Black,Medium,Female,FIV positive,NaN,"Vaccinations up to date, spayed / neutered, sp...",NaN,NaN,NaN,NaN,180.0,Best Friends Animal Society - East Coast Lifeâ€¦,thirty_day_spec_needs,1

In [65]:
all = pd.concat([combined_all, spec_needs_combined], axis = 0, sort=False)

all.to_csv('out_all.csv')  #dpg exports to a csv file

all.head()

,cat_name,num_images,num_videos,age,breed,color,size,sex,characteristics,house_trained,health,good_in_a_home_with,adoption_fee,prefers_a_home_without,coat_length,pet_story_num_words,rescue_group,data_set,num_cats
0,Ashe and Billie,6,0,Adult,Domestic Short Hair,NaN,Medium,Female,NaN,Yes,"Vaccinations up to date, spayed / neutered.",NaN,NaN,NaN,NaN,89.0,KittyKind,one_day,1
1,Billie and Ashe,6,0,Adult,Domestic Short Hair,NaN,Medium,Female,NaN,Yes,"Vaccinations up to date, spayed / neutered.",NaN,NaN,NaN,NaN,89.0,KittyKind,one_day,1
2,Holiday Hibiscus,2,0,Kitten,Domestic Short Hair,Gray / Blue / Silver,Medium,Male,NaN,Yes,Vaccinations up to date.,"Other cats, children.",NaN,NaN,Short,126.0,Liberty Humane Society,one_day,1
3,"Favorite Babies-Wonton, Lichee, Sprout & Dumpling",3,0,Kitten,Domestic Short Hair,White,Small,Male,NaN,Yes,NaN,Other cats.,NaN,NaN,NaN,313.0,Brooklyn Animal Action,one_day,1
4,Romeo and Guero,4,0,Young,Domestic Short Hair,NaN,Medium,Male,"Friendly, Affectionate, Gentle, Playful",Yes,"Vaccinations up to date, spayed / neutered.",NaN,NaN,NaN,Medium,149.0,The Lucky Cat Rescue,one_day,1